---
# group vars file for Infrastructure Culture
# dev_env.yml - variables that carry to the development environment
####################################
# <common vars for dev>
####################################
deploy_environment: dev
resource_group: dev_rg
####################################
# </common vars for dev>
####################################
####################################
# <IAM>
####################################
aws_iam_groups:
  - aws_devs
  - aws_testers
  - aws_sysadmins
aws_iam_users:
  - bmw325u
  - bmw525u
aws_iam_roles:
  - bmw325r
  - bmw525r
aws_iam_dev_users:
  - bmw325u
  - bmw525u
aws_iam_tester_users:
  - bmw325u
  - bmw525u
aws_iam_sysadmin_users:
  - bmw325u
  - bmw525u
####################################
# </IAM>
####################################
####################################
# <VPC>
####################################
vpc_resource_tags: { "Name":"ansible_dev_vpc", "deploy_environment":"{{ deploy_environment }}", "resource_group":"{{ resource_group }}" }
az_a_resource_tags: { "Name":"ansible_az_a", "deploy_region":"{{ aws_region }}", "deploy_environment":"{{ deploy_environment }}", "deploy_az":"a", "resource_group":"{{ resource_group }}" }
az_b_resource_tags: { "Name":"ansible_az_b", "deploy_region":"{{ aws_region }}", "deploy_environment":"{{ deploy_environment }}", "deploy_az":"b", "resource_group":"{{ resource_group }}" }
az_c_resource_tags: { "Name":"ansible_az_c", "deploy_region":"{{ aws_region }}", "deploy_environment":"{{ deploy_environment }}", "deploy_az":"c", "resource_group":"{{ resource_group }}" }
az_a_external_resource_tags: { "Name":"ansible_ex_az_a", "deploy_region":"{{ aws_region }}", "deploy_environment":"{{ deploy_environment }}", "deploy_az":"external_a", "resource_group":"{{ resource_group }}" }
az_b_external_resource_tags: { "Name":"ansible_ex_az_b", "deploy_region":"{{ aws_region }}", "deploy_environment":"{{ deploy_environment }}", "deploy_az":"external_b", "resource_group":"{{ resource_group }}" }
az_c_external_resource_tags: { "Name":"ansible_ex_az_c", "deploy_region":"{{ aws_region }}", "deploy_environment":"{{ deploy_environment }}", "deploy_az":"external_c", "resource_group":"{{ resource_group }}" }
vpc_igw_resource_tags: { "Name":"ansible_igw", "deploy_environment":"{{ deploy_environment }}", "deploy_region":"{{ aws_region }}", "resource_group":"{{ resource_group }}" }
vpc_public_route_table_resource_tags: { "Name":"ansible_public_route", "deploy_environment":"{{ deploy_environment }}", "deploy_region":"{{ aws_region }}", "resource_group":"{{ resource_group }}"}
vpc_private_route_table_resource_tags: { "Name":"ansible_private_route", "deploy_environment":"{{ deploy_environment }}", "deploy_region":"{{ aws_region }}", "resource_group":"{{ resource_group }}"}
####################################
# </VPC>
####################################
####################################
# <S3>
####################################
aws_s3_buckets:
  - simplifymybizdev.bucket1.{{ aws_region }}
  - simplifymybizdev.bucket2.{{ aws_region }}
aws_s3_bucket_tags: { "Name":"simplifymybizdev_s3_bucket", "deploy_region":"{{ aws_region }}", "deploy_environment":"{{ deploy_environment }}", "resource_group":"{{ resource_group }}"}
aws_s3_days_till_freeze: 30
aws_s3_days_till_destroy: 90
aws_s3_log_prefix_to_freeze: /logs/
####################################
# </S3>
####################################
####################################
# <Ansible Tower>
####################################
tower_ami: ami-826da0e2
# region ami:
# US West Oregon us-west-2 = ami-826da0e2
# US West Cali us-west-1 = 	ami-4f56172f
# US East Ohio us-east- =
# US East Virgina us-east-1 = ami-6e008e79
# Euro West Ireland = ami-4c73103f
# Euro West UK =
# Euro East Germany = ami-3cb74353
tower_keypair: smb_tower_keys
tower_instance_type: t2.small
tower_sec_grp: tower_sec_grp
tower_iam_profile: tower_iam_profile
tower_instance_tags: { "Name":"smb_ansible_tower", "deploy_region":"{{ aws_region }}", "deploy_environment":"{{ deploy_environment }}", "resource_group":"{{ resource_group }}"}
####################################
# </Ansible Tower>
####################################
####################################
# <RDS>
####################################
aws_rds_instance_name:
  - rds_db_1
aws_rds_db_engine: mysql
aws_rds_db_disk_size: 10
aws_rds_db_instance_type: t2.medium
aws_rds_db_username: smb_rds_users_1
aws_rds_db_password: teCSzMiLVxEHGoyDQbAown
aws_rds_db_tags: { "Name":"smb_rds_db_1", "deploy_region":"{{ aws_region }}", "deploy_environment":"{{ deploy_environment }}", "resource_group":"{{ resource_group }}"}
####################################
# </RDS>
####################################
####################################
# </end of dev_env.yml>
####################################
...