---
# tasks file for roles/aws_route53

- name: deploy a route53 DNS entry
  route53:
    command: create
    zone: simplifymy.cloud
    record: lets.simplifymy.biz
    type: A
    ttl: 7200
    value: 1.1.1.1,2.2.2.2,3.3.3.3
    wait: yes
...