---
  # aws_route53_test.yml - playbook to ensure the state of the route53
  # in the test environment

- name: ensure the security group state for test environment
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - group_vars/test.yml

  roles:
    - aws_route53

  tags:
    - aws_test_env
    - aws_route53
...