---
  # aws_secgrp_dev.yml - playbook to ensure the state of the secgrp
  # in the development environment

- name: ensure the security group state for dev environment
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - group_vars/dev.yml

  roles:
    - aws_secgrp

  tags:
    - aws_dev_env
    - aws_secgrp
...