---
  # aws_route53_production.yml - playbook to ensure the state of the route53
  # in the production environment

- name: ensure the security group state for production environment
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - group_vars/production.yml

  roles:
    - aws_route53

  tags:
    - aws_production_env
    - aws_route53
...