---
  # aws_vpc_stage.yml - playbook to ensure the state of the VPC
  # in the stage environment

- name: ensure a vpc is deployed for stage environment
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - group_vars/stage.yml

  roles:
    - aws_vpc

  tags:
    - aws_stage_env
    - aws_vpc
...