---
  # aws_route53_stage.yml - playbook to ensure the state of the route53
  # in the stage environment

- name: ensure the security group state for stage environment
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - group_vars/stage.yml

  roles:
    - aws_route53

  tags:
    - aws_stage_env
    - aws_route53
...