---
  # aws_vpc_test.yml - playbook to ensure the state of the VPC
  # in the test environment

- name: ensure a vpc is deployed for test environment
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - group_vars/test_env.yml

  roles:
    - aws_vpc

  tags:
    - aws_test_env
    - aws_vpc
...