---
  # aws_vpc_dev.yml - playbook to ensure the state of the VPC
  # in the development environment

- name: ensure a vpc is deployed for dev environment
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - group_vars/dev.yml

  roles:
    - aws_vpc

  tags:
    - aws_dev_env
    - aws_vpc
...