---
  # aws_iam_production.yml - playbook to ensure the state of the iam
  # in the production environment

- name: ensure the security group state for production environment
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - group_vars/production.yml

  roles:
    - aws_iam

  tags:
    - aws_production_env
    - aws_iam
...