---
  # production_foundation_state.yml
  # define the foundation layer using the production 
  # environment vars file

  - name: ensure the foundation state for the production env
    hosts: localhost
    connection: local
    gather_facts: no

    vars_files:
      - group_vars/production_env.yml

    roles:
      - aws_vpc
      - aws_iam
      - aws_secgrp
      #- aws_route53

    tags:
      - production_env
      - foundation
...