---
# tasks file for roles/aws_secgrp

- name: ensure the vpc has a security group with rules for each piece of the stack
  ec2_group:
    name: "{{ deploy_environment }}_sec_group"
    description: "VPC security group for the {{ deploy_environment }} environment"
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ aws_region }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: all
        from_port: 
        to_port: 
        cidr_ip: "10.{{ region_octet }}.0.0/16"
...